### ISSUE TITLE
Fix test case: LivenessTest

### ISSUE THREAD

**Issue by Thalmann** [python-security/pyt#1]
See commit: https://github.com/python-security/pyt/commit/d2418ef028436bd8c4419aa31823cf8291ecafe6

**Comment by Thalmann** [comment]
Actually this could be fixed by running it with python 3.6 as dicts are ordered there :b

**Comment by KevinHock** [comment]
I'll figure this one out 👍  It _seems_ easy enough to fix w/out the ordered dicts.

**Comment by KevinHock** [comment]
I guess we can close this one now

**Comment by Thalmann** [comment]
Yes TY! :)
