### ISSUE TITLE
Baseline support

### ISSUE THREAD

**Issue by KevinHock** [python-security/pyt#101]
Once https://github.com/python-security/pyt/pull/100 is merged this will be do-able.

So a baseline is for when you want to diff between a previous run, (probably of known issues or false-positives) and a current run, 'as a big part of continuous integration', baseline support is super important.

See https://github.com/openstack/bandit as a tool that implements this.

```python
    parser.add_argument('-b', '--baseline',
                        help='path of a baseline report to compare against '
                             '(only JSON-formatted files are accepted)',
                        type=str,
                        default=None)
```

There is also the newly open sourced [`detect-secrets` repo](https://github.com/Yelp/detect-secrets/blob/b16acf1e8dc1e05366a9bfbd7ce35ed611adb94d/detect_secrets/core/baseline.py#L41) from the Yelp security team that implements this.

**Comment by KevinHock** [comment]
Would you like to take this one @omergunal?

**Comment by omergunal** [comment]
Sure, i will work on this

**Comment by KevinHock** [comment]
🎉
