### ISSUE TITLE
Pinned requirements in setup.py

### ISSUE THREAD

**Issue by MacBox7** [python-security/pyt#104]
Is it really necessary to pin requirements to a specific version which is being done in `setup.py`?
```
install_requires=[
        'graphviz==0.4.10',
        'GitPython==2.0.8'
]
```
Because pinning requirements can cause version conflicts with other projects working in the same environment. The best practice would be to set a minimum version(as low as possible) for which the project would work.

**Comment by KevinHock** [comment]
@MacBox7 You're totally right about this, it's kind of crust left over from over a year ago, I shall fix it soon. 👍 Thank you for bringing it up.
