### ISSUE TITLE
Feature Request: Whitelist lines ending in # nosec

### ISSUE THREAD

**Issue by KevinHock** [python-security/pyt#108]
So both [detect-secrets](https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/plugins/high_entropy_strings.py#L41) and Bandit have the concept of whitelisting a line by putting a comment at the end, similar to how you've probably seen people do `# noqa: F401` or whatever, with pylint.

Let us steal once again, from Bandit, since they are most similar to us, [here are the relevant lines](https://github.com/openstack/bandit/blob/8f09d8b208f037b7d49ed6bc88f2ac200e7cc06c/bandit/core/manager.py#L270-L277), but we shall change `lineno + 1 for` to `enumerate(lines, start=1)` because it is more pythonic.

They also have the `--ignore-nosec        do not skip lines with # nosec comments` command line option` so we shall pass in the set of lines to the 2 calls to `find_vulnerabilities` [in \_\_main\_\_](https://github.com/python-security/pyt/blob/master/pyt/__main__.py#L53),

**Comment by KevinHock** [comment]
While I initially thought we would just give the option to add `# nosec` to the sinks, e.g.

```
@app.route('/menu', methods=['POST'])
def menu():
    param = request.form['suggestion']
    command = 'echo ' + param + ' >> ' + 'menu.txt'

    subprocess.call(command, shell=True)  # nosec

    with open('menu.txt','r') as f:
        menu = f.read()

    return render_template('command_injection.html', menu=menu)
```

We can, without writing any more lines of code, give the option to add `# nosec` to the sources, e.g.

```python
@app.route('/menu', methods=['POST'])
def menu():
    param = request.form['suggestion']  # nosec
    command = 'echo ' + param + ' >> ' + 'menu.txt'

    subprocess.call(command, shell=True)

    with open('menu.txt','r') as f:
        menu = f.read()

    return render_template('command_injection.html', menu=menu)
```

This may be the preference of a security team, as the code may change in the future, and it's more dangerous to have the sink be whitelisted, because there may be multiple [vuln chains](https://github.com/python-security/pyt/pull/81).

**Comment by KevinHock** [comment]
Would you like to take this one, @omergunal?

**Comment by omergunal** [comment]
sure

**Comment by KevinHock** [comment]
I forgot to say this before, but after passing the set of lines to `find_vulnerabilities` we can ignore both sources and sinks in the same function, [find_triggers](https://github.com/python-security/pyt/blob/master/pyt/vulnerabilities.py#L171-L185), something like `if node.lineno not in nosec_lines:`

**Comment by KevinHock** [comment]
Woohoo 👍
