### ISSUE TITLE
Tags: 'final' and 'finalfinal'

### ISSUE THREAD

**Issue by mboelen** [python-security/pyt#124]
Hi team,

Thanks for your project. We added [Pyt](https://linuxsecurity.expert/tools/pyt/) to our security tools section. While reviewing we noticed we could only extract tags from the GitHub repo, as no releases are used. Now tags are sorted by alphabet, meaning that the tagged version 'finalfinal' always is listed as the highest release number. Not sure if it is possible, but you could re-tag it 'final' and 'finalfinal'. Then the community can pick up future released and promote your project. Otherwise, it gets stuck on a very old version ;-)

**Comment by KevinHock** [comment]
I'll try getting all releases and tags deleted that aren't 0.34 (since .34 is the only one documented in the changelog and the latest version.)

**Comment by KevinHock** [comment]
Git tags are pretty permanent AFAIK though, we'll see

**Comment by mboelen** [comment]
Thanks. [This link](https://stackoverflow.com/questions/6151970/how-do-you-remove-a-tag-from-a-remote-repository#6151985) might be helpful?

**Comment by KevinHock** [comment]
Quite helpful indeed @mboelen :D This should be fixed

**Comment by mboelen** [comment]
Thanks, it shows 0.34 now on our tool page :)

**Comment by KevinHock** [comment]
Awesome! :D
