### ISSUE TITLE
Add a "don't ask me anymore" option to the interactive mode

### ISSUE THREAD

**Issue by KevinHock** [python-security/pyt#128]
this is where we ask for input in vulnerabilities.py

**Comment by prithvisingh18** [comment]
Hi, can I try to solve this issue ?

**Comment by KevinHock** [comment]
Hi prithvisingh, definitely 👍🙏

I'll try to make the issue description etc. better later today, but for understanding the code a bit more see this pr https://github.com/python-security/pyt/pull/81 :)
