### ISSUE TITLE
[cfg] We don't visit functions in while loops

### ISSUE THREAD

**Issue by KevinHock** [python-security/pyt#133]
You can see we do it for `for` loops and not while loops https://github.com/python-security/pyt/blob/346a2d3070f70efbf81be44c261f356ba6fc0f1c/pyt/cfg/stmt_visitor.py#L513-L529

**Comment by KevinHock** [comment]
I think reading the [cfg readme] is a good start on this https://github.com/python-security/pyt/tree/master/pyt/cfg

**Comment by KevinHock** [comment]
Hi @omergunal, would you like to take this one?

**Comment by omergunal** [comment]
i would :tada:
