### ISSUE TITLE
Add new language features from 3.6 to cfg

### ISSUE THREAD

**Issue by Thalmann** [python-security/pyt#14]

**Comment by bcaller** [comment]
We can probably close this one.

New syntax features:
PEP 498, formatted string literals. works #142
PEP 515, underscores in numeric literals. nothing to do here
PEP 526, syntax for variable annotations. added #143
PEP 525, asynchronous generators. When we add support for 3.5 syntax this should come for free.
PEP 530: asynchronous comprehensions. ast node is like a normal comprehension but with an async flag so nothing to do here

**Comment by KevinHock** [comment]
Great point, thank you so much!
