### ISSUE TITLE
Search the code base for each repo

### ISSUE THREAD

**Issue by Thalmann** [python-security/pyt#15]
Right now we search overall on a string in github search
Search more specific on each repo
This could give better results and maybe lesser requests per minute
But this off course could also give more requests per minute as it would take two requests per repo

**Comment by KevinHock** [comment]
Now that PyT is on PyPi, I think it would be best if I made a separate repo for the GitHub scanner code, for a clean separation between the two. Like [`detect-secrets`](https://github.com/Yelp/detect-secrets) and [`detect-secrets-server`](https://github.com/Yelp/detect-secrets-server). We can reference it from the README.
