### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by bcaller** [python-security/pyt#154]
Would be great to get a new release published on pypi soon.

We have over 190 commits added, though I'm not sure of the specific criteria for bumping the version.

**Comment by KevinHock** [comment]
I can definitely do this one 😊 I'll make the CHANGELOG PR soon too.

**Comment by KevinHock** [comment]
There is a hackathon tomorrow and Friday, so I'll be working on my open PR.

But I'll do this ticket on Saturday, note to self:
```python
[Bump the version in setup.py!]
[I like to source into a python36 env]
git tag
git tag X.Y.Z -m""
git tag
git push --tags origin master
rm -rf build/ dist/;python setup.py sdist;python setup.py bdist_wheel
twine upload --repository-url https://test.pypi.org/legacy/ dist/*

pip install detect-secrets -i https://test.pypi.org/simple/
[Test that it looks good]

[Final steps: Upload to real PyPi]
twine upload dist/*
```

**Comment by KevinHock** [comment]
I've updated the [changelog](https://github.com/python-security/pyt/blob/master/CHANGELOG.md) and bumped the version, but something is very wrong with `pip` on my laptop 😟 I'll have to do the PyPI stuff on Monday.

**Comment by bcaller** [comment]
Yeah no worries, pip messes me around sometimes as well.

**Comment by KevinHock** [comment]
So in setup.py it was

```python
'pyt = pyt:main'
```

Then I made [my __init__ commit](https://github.com/python-security/pyt/commit/aae962534e941fa8f58c3e40ae4b51b520707f42#diff-cc957785bef379578cab0e0ceba1ed0a) to fix https://stackoverflow.com/questions/43393764/python-3-6-project-structure-leads-to-runtimewarning

Which broke the above `pyt = pyt:main` and gave a `ImportError: module 'pyt' has no attribute 'main'` error.

You fixed this in [your setup.py commit](https://github.com/python-security/pyt/commit/d4cbde04fc9c30c875244f17e0fe25aba48ffe17#diff-2eeaed663bd0d25b7e608891384b7298), but now when doing `pyt --help` it gives `ImportError: No module named 'pyt.analysis'`, I'll investigate.

**Comment by KevinHock** [comment]
So hopefully https://github.com/python-security/pyt/commit/76be3218525b7b24b567a709a5ebd492c0ab8585 and bumping to `0.37` worked, PyPI might be being slow b/c I can't `pip install` it yet. 

Later on I'll update the CHANGELOG to include the PR of yours I merged today. 👍

**Comment by KevinHock** [comment]
Updated the `CHANGELOG` as well 😉  https://github.com/python-security/pyt/commit/5b7d06b0ec5840b69f41d3678930fc6a2675d311
