### ISSUE TITLE
No requirements.txt as mentioned in docs

### ISSUE THREAD

**Issue by peacepirate** [python-security/pyt#159]
The readme mentions pip install -r requirements.txt, but the master branch does not seem to have a requirements.txt. Have the dependencies been removed completely? Seems like the installation instructions should be to run the setup.py or:
`pip install -e pyt`

**Comment by KevinHock** [comment]
🙇 🙏  That's a great point @peacepirate, sorry about that, that change happened recently. I'll update the `README.rst` more extensively today or tomorrow.

Thanks for bringing that to my attention!

**Comment by KevinHock** [comment]
I removed the `requirements` part in the meantime https://github.com/python-security/pyt/commit/d626efc6c45dc9cfdee4737dd4957f1047f1cf6a

**Comment by KevinHock** [comment]
I made the readme a little better with a how to use section, I still have to write a walkthrough, but that's an Issue already made.
👍
