### ISSUE TITLE
Check why travis is failing

### ISSUE THREAD

**Issue by Thalmann** [python-security/pyt#16]
This issues is solved when a description of why travis is failing and a way to fix it is done

**Comment by KevinHock** [comment]
Is it running it as Python 2 and not 3? 🤔

**Comment by KevinHock** [comment]
The results file was bad :) Fixed it in my latest PR here https://github.com/python-security/pyt/pull/23

**Comment by Thalmann** [comment]
Great, i reviewed your changes.
Can you put this into a separate PR and i can accept it.
