### ISSUE TITLE
Add a logger and verbosity options

### ISSUE THREAD

**Issue by KevinHock** [python-security/pyt#168]
So after https://github.com/python-security/pyt/pull/99 is merged, we will be be pretty accurate, accurate enough for us to shift our focus towards making the tool more resilient and able to run on lots and lots of repos.

PyT needs to be more user-friendly by letting the user know e.g. which files it is looking at, and also more resilient, logging will help with fixing issues like RecursionDepth errors etc.

Here is a logging PR that is pretty good we can take things from https://github.com/Yelp/detect-secrets/pull/46

**Comment by bcaller** [comment]
Initial logging framework added in #172.

**Comment by KevinHock** [comment]
Good point, I forgot to close 👍
