### ISSUE TITLE
Implement github_oath_token as a configuration

### ISSUE THREAD

**Issue by StefanMich** [python-security/pyt#17]
see github_search.py

https://docs.python.org/3/library/configparser.html
http://stackoverflow.com/questions/2026876/packaging-python-applications-with-configuration-files

**Comment by KevinHock** [comment]
Now that PyT is on PyPi, I think it would be best if I made a separate repo for the GitHub scanner code, for a clean separation between the two. Like [`detect-secrets`](https://github.com/Yelp/detect-secrets) and [`detect-secrets-server`](https://github.com/Yelp/detect-secrets-server). We can reference it from the README.
