### ISSUE TITLE
[Question] Is pyt adaptable to command line applications?

### ISSUE THREAD

**Issue by fkromer** [python-security/pyt#176]
I was wondering if it's possible to use pyt with / adapt pyt to command line applications? The implementation of pyt in this repository seems to based on the [source code](https://github.com/SW10IoT/pyt/tree/finalfinal) of this [thesis](https://projekter.aau.dk/projekter/files/239563289/final.pdf)? Has there changed something significantly from highest level view in the meanwhile one needs to know to understand the current high level functionality?

In case of a command line application the [`sources`](https://github.com/python-security/pyt/blob/master/pyt/vulnerability_definitions/all_trigger_words.pyt#L2) would probably be command line interface arguments and options. The `sinks` could probably be some of the web framework [sinks](https://github.com/python-security/pyt/blob/master/pyt/vulnerability_definitions/all_trigger_words.pyt#L21) (`subprocess.call`, `Popen(`, etc.).

**Comment by bcaller** [comment]
It should work for command line applications. You just need to configure the sources of taint which will be `sys.argv` or `.parse_args(` and configure the sinks. You can remove the flask / django related functions from your triggers file. Might also want an adaptor which just starts at the main function, not sure off the top of my head.

**Comment by fkromer** [comment]
The entry points to the standard library command line parsers are either `sys.argv` or explicitly passed args.

* [argparse](https://docs.python.org/3.7/library/argparse.html): [`.parse_args(`](https://docs.python.org/3.7/library/argparse.html#argparse.ArgumentParser.parse_args) (uses ` sys.argv` by default or explicitly passed args)
* [optparse](https://docs.python.org/3/library/optparse.html): `parse_args(` (uses `sys.argv[1:]` by default or explicitly passed args)
* [getopt](https://docs.python.org/3/library/getopt.html): [`.getopt(`](https://docs.python.org/3/library/getopt.html#getopt.getopt), [`.gnu_getopt(`](https://docs.python.org/3/library/getopt.html#getopt.gnu_getopt)

As far as I know all other libraries like e.g. [`click`](https://github.com/pallets/click) (uses [fork of `optparse`](https://click.palletsprojects.com/en/7.x/why/#why-click)) built upon one of the standard lib command line parsers.

**Comment by bcaller** [comment]
Yes, so add the functions to your triggers file. I think it should just work. Try it.

**Comment by fkromer** [comment]
I'll give it a try. I am just not sure how yet... :smile: [`Documentation coming soon.`](https://github.com/python-security/pyt/blob/master/pyt/vulnerability_definitions/README.rst)

**Comment by fkromer** [comment]
`pyt` is adaptable to `sys.argv` based command line applications. Checkout the example on my fork [examples/vulnerable_code/cla.py](https://github.com/fkromer/pyt/blob/cla/examples/vulnerable_code/cla.py). (Probably not the best location for `cla.py`. Anyway... it works.)
