### ISSUE TITLE
Add support for sinks introduced with "from .... import ..." 

### ISSUE THREAD

**Issue by fkromer** [python-security/pyt#177]
Right now sinks seem to be considered during vulnerability analysis only in case of "module scope imports". E.g. vulnerabilities w.r.t. [sink `subprocess.call(`](https://github.com/python-security/pyt/blob/master/pyt/vulnerability_definitions/all_trigger_words.pyt#L36) are only detected in case the production code imports module scope wise:

```
import subprocess

subprocess.call(
```

In case the production code introduces the sink via module import the vulnerability won't be detected.

```
from subprocess import call

call(
```

**Comment by bcaller** [comment]
Yep. It's the same with `import x as y`. I would like pyt to resolve fully qualified names where possible. I think whoever works on this should look at how bandit does this.

**Comment by KevinHock** [comment]
This would definitely be a great feature

**Comment by fkromer** [comment]
> Yep. It's the same with import x as y. I would like pyt to resolve fully qualified names where possible. I think whoever works on this should look at how bandit does this.

If one looks at Bandit examples of [`B602`](https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html), [`B603`](https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html) and [`B604`](https://bandit.readthedocs.io/en/latest/plugins/b604_any_other_function_with_shell_equals_true.html) it seems like Bandit doesn't consider this either. In case `Popen` is imported as `pop` via [`from subprocess import Popen as pop`](https://github.com/PyCQA/bandit/blob/a41cd90cfa493973b83a0894364964b7e55fe0fe/examples/subprocess_shell.py#L2) the example of [`B604`](https://bandit.readthedocs.io/en/latest/plugins/b604_any_other_function_with_shell_equals_true.html) doesn't document a raise `pop('/bin/gcc --version', shell=True)`.

**Comment by adrianbn** [comment]
I am interested in this, and in general in being able to identify sinks in a better way than currently. I tried bandit 1.5.1 on python 3.7.0 and the following code triggers B604:

```python
from subprocess import Popen as pop

pop('/bin/ls', shell=True)
```

```Test results:
>> Issue: [B404:blacklist] Consider possible security implications associated with Popen module.
   Severity: Low   Confidence: High
   Location: test-bandit.py:1
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_imports.html#b404-import-subprocess
1       from subprocess import Popen as pop
2
3       pop('/bin/ls', shell=True)

--------------------------------------------------
>> Issue: [B602:subprocess_popen_with_shell_equals_true] subprocess call with shell=True seems safe, but may be changed in the future, consider rewriting without shell
   Severity: Low   Confidence: High
   Location: test-bandit.py:3
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html
2
3       pop('/bin/ls', shell=True)```

Is there a reason why sinks are defined like this `subprocess.call(`? Wouldn't it be better to define the package and method separately and include which argument of the function is actually not supposed to receive tainted data?

**Comment by amacfie** [comment]
Close?

**Comment by KevinHock** [comment]
Thanks @amacfie!
