### ISSUE TITLE
Add missing shell injection sinks

### ISSUE THREAD

**Issue by fkromer** [python-security/pyt#180]
We should add missing `sinks` w.r.t. "shell injection" to  [`all_trigger_words.py`](https://github.com/python-security/pyt/blob/master/pyt/vulnerability_definitions/all_trigger_words.pyt). Refer to [Bandit plugin `shell_injection`](https://github.com/PyCQA/bandit/blob/master/bandit/plugins/injection_shell.py) for more info.

**Comment by Nishant23** [comment]
@KevinHock How can I help in this? I am new to this project.

**Comment by KevinHock** [comment]
Oh no, totally missed the email notification for this, my bad.
