### ISSUE TITLE
Refactor: base_test_case.py

### ISSUE THREAD

**Issue by Thalmann** [python-security/pyt#19]

**Comment by KevinHock** [comment]
How would you like it refactored?

**Comment by Thalmann** [comment]
First off the code style, then this is the BaseTestCase so it should be that and not have CFG specific test methods in it.
So we need a BaseCFGTestCase or something like that. That inherits from the base.
And so on if there are other more specific methods in there.

**Comment by KevinHock** [comment]
I did this in another branch already, gonna merge in a week or two, but I figured I would close this now.
