### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by Thalmann** [python-security/pyt#2]
use .rst format so it also can be used for pypi packaging

**Comment by Toughee** [comment]
I'm working on this right now. Can I be assigned to this?

**Comment by Thalmann** [comment]
Great, i send you an invite to become a collaborator :)

**Comment by Toughee** [comment]
I'm finished reformatting everything. I'm sending a pull request now.

**Comment by KevinHock** [comment]
Should we close it now, thanks to https://github.com/python-security/pyt/pull/41, @Thalmann?

**Comment by Thalmann** [comment]
Yes, i thought i already did that..
