### ISSUE TITLE
More user friendly menu

### ISSUE THREAD

**Issue by Thalmann** [python-security/pyt#27]
Custom error messages
Better description of how to use it
Maybe more in depth readme

**Comment by KevinHock** [comment]
I'm not sure what was meant by `Custom error messages` but I'm doing the latter 2 parts as part of https://github.com/python-security/pyt/issues/113 So I think I'll close this one as a duplicate. 

Game plan as follows, if curious: (1) finish current open PR (to fix false-negatives around not handling expr*/boolop/ifexp/etc.) (2) make my class-based views branch a PR (3) add a more in-depth README with configuring PyT and an example walk through, (4) ssrf evaluation.
