### ISSUE TITLE
pypi packaging

### ISSUE THREAD

**Issue by Thalmann** [python-security/pyt#3]

**Comment by Thalmann** [comment]
Nået til entry_points -> https://packaging.python.org/distributing/#entry-points
Skal det igennem en metode eller kan vi bare angive pyt.py?

**Comment by MacBox7** [comment]
Till when will it be available from pypi repository?

**Comment by KevinHock** [comment]
@MacBox7 I'm going to be working on a super cool interactive mode in the short-term https://github.com/python-security/pyt/pull/81 and, in the long-term, fixing issues from 
[past_evaluations](http://pyt.readthedocs.io/en/latest/past_evaluations.html). So unfortunately I don't see myself working on this until over a year from now.

If you would like to take this issue on I would greatly appreciate it, I'll help you along the way if you hit any roadblocks.

**Comment by MacBox7** [comment]
I don't think publishing on pypi is that big of a task. Plus it requires you to have an account on pypi live and pypi test. So, won't it be better for you to upload it? I don't mind working on it. Should I publish using my credentials?

**Comment by KevinHock** [comment]
You can publish using your credentials, the name pyt is taken (I messaged Bruno about it a while ago, but this issue hasn't been worked on in a while) so you can name it maybe python-taint or junkhacker or really whatever you prefer ;)

Thank you for working on this 🙏

**Comment by MacBox7** [comment]
Execute this `git tag 0.1 -m "Adds a tag so that we can put this on PyPI."`. Need this to generate a tar ball that will be used while uploading. Then execute `git push --tags origin master`. There are already two tags though named as `final` and `finalfinal` and I am not sure which one to use.

**Comment by polyzen** [comment]
A new release would be A+.

**Comment by KevinHock** [comment]
Will due this as soon as I get home 👍

**Comment by KevinHock** [comment]
Should be done now https://github.com/python-security/pyt/releases

**Comment by MacBox7** [comment]
@KevinHock Have you tested your commits done on `Mar 1, 2018 `. The setup.py is failing. Try creating a new virtualenv and install pyt. It fails :(

**Comment by KevinHock** [comment]
Sure thing 👍 It's 11:23pm now but I'll do this at work tomorrow lol :)

**Comment by KevinHock** [comment]
So I think it might be that it needs to be python 3.6, or that you might need to uninstall it and try again or create a new virtualenv if it already had `pyt==1.0.0a20`.

Here is what I did that worked:
`virtualenv -p python3.6 three_six;source three_six/bin/activate`
then
`git clone https://github.com/python-security/pyt`
then
`python --version` to make sure I'm on Python 3.6.0
then
`python setup.py install`
and
e.g.
`pyt --help` should work.

What was the error that you got?

**Comment by polyzen** [comment]
FWIW, it builds and passes all tests on Arch Linux with more permissive dependency version specifiers:
https://aur.archlinux.org/packages/pyt/
https://aur.archlinux.org/packages/pyt-git/

**Comment by MacBox7** [comment]
Yes, you are right it works for Python3.6.
I was using Python3.5 for which it gave the following error : 
```
Traceback (most recent call last):
  File "/home/ankit/virtualenvironment/test/bin/pyt", line 11, in <module>
    load_entry_point('pyt==1.0.0a20', 'console_scripts', 'pyt')()
  File "/home/ankit/virtualenvironment/test/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ankit/virtualenvironment/test/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/ankit/virtualenvironment/test/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/ankit/virtualenvironment/test/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ankit/virtualenvironment/test/lib/python3.5/site-packages/pyt-1.0.0a20-py3.5.egg/pyt/__init__.py", line 1, in <module>
    from .__main__ import main
  File "/home/ankit/virtualenvironment/test/lib/python3.5/site-packages/pyt-1.0.0a20-py3.5.egg/pyt/__main__.py", line 14, in <module>
    from .framework_adaptor import FrameworkAdaptor
  File "/home/ankit/virtualenvironment/test/lib/python3.5/site-packages/pyt-1.0.0a20-py3.5.egg/pyt/framework_adaptor.py", line 9, in <module>
    from .interprocedural_cfg import interprocedural
  File "/home/ankit/virtualenvironment/test/lib/python3.5/site-packages/pyt-1.0.0a20-py3.5.egg/pyt/interprocedural_cfg.py", line 277
    save_name = f'save_{saved_function_call_index}_{assignment.left_hand_side}'
                                                                              ^
SyntaxError: invalid syntax
```
I think it would be better if pyt is backwards compatible with at least all version of Python3.
