### ISSUE TITLE
Add CodeClimate

### ISSUE THREAD

**Issue by KevinHock** [python-security/pyt#35]
E.g. If we look at https://github.com/trailofbits/protofuzz we can see the test coverage at the top and a link to code climate.

To fix this we more or less copy the codeclimate.yml and relevant parts of the top of the README.

(So the [easy] issues are good for new people who want to start contributing to look at.)

**Comment by KevinHock** [comment]
So I'm gonna do this one now that `__init__` files are done :D

**Comment by morrme** [comment]
I looked at it but I am not an owner/admin so I couldn't do much.

**Comment by Thalmann** [comment]
So i do not know anything about codeclimate. I have signed our repo up here: https://codeclimate.com/github/python-security/pyt
Let me know this is what was missing? :slightly_smiling_face:

**Comment by KevinHock** [comment]
I think it's a matter of troubleshooting and then editing the Travis yml and figuring out how we should generate a .coverage in the Travis yml. (Since we aren't using nose in the example I gave.) https://github.com/python-security/pyt/pull/43

**Comment by KevinHock** [comment]
All done, was pretty easy once I forked https://github.com/python-security/pyt/pull/44

**Comment by KevinHock** [comment]
Thanks @Thallman 👍
