### ISSUE TITLE
Add readthedocs 

### ISSUE THREAD

**Issue by KevinHock** [python-security/pyt#36]
If you look at https://github.com/trailofbits/manticore/blob/master/README.md you can see a nice link at the top to the docs. I'll write the docs once the layout is there, please see 
https://www.slideshare.net/mobile/JohnCosta/how-to-readthedocs

(So the [easy] issues are good for new people who want to start contributing to look at.)

**Comment by morrme** [comment]
I'd like to help with this.

**Comment by Thalmann** [comment]
Great,

If you want we can discuss it on slack? Set me an email: mr.thalmann@gmail for invite
Else if you have any questions feel free to ask them here.

**Comment by morrme** [comment]
@Thalmann thanks! i am revewing the instructions once more and i'll have questions after that.

**Comment by KevinHock** [comment]
@morrme Would you like me to help you w/ this issue? 
I found the following that seem like they'll be helpful, I've never done it before though.
http://dont-be-afraid-to-commit.readthedocs.io/en/latest/documentation.html
http://docs.readthedocs.io/en/latest/getting_started.html

 If it requires Admin perms you can always create a fork like I'm trying to w/ the Codeclimate issue, https://codeclimate.com/github/KevinHock/codeclimatepyt/coverage (still need to do the Travis YML stuff tonight.)

I could try my hand at it and show you what I did if you'd like. Let me know what you think.

**Comment by morrme** [comment]
@KevinHock i sent a message on slack about this , i love the idea of doing it on a fork to get the process together. i will work on it !

**Comment by KevinHock** [comment]
Awesome, thanks @morrme :)

**Comment by KevinHock** [comment]
I kind of feel bad about this :/ But I started documenting http://pyt.readthedocs.io/en/latest/?badge=latest via https://github.com/KevinHock/rtdpyt. I'm sorry.

**Comment by morrme** [comment]
you should not feel bad. i had a few troubles with mine and clearly you got past it.  I initially grabbed the pyt name for my fork and released it so that it would be available. :) glad you got it!

**Comment by KevinHock** [comment]
I'm still working on documenting everything but felt it was good enough to add the badge, once I feel it's more complete I'll make the PR to move my docs/ folder to this repo. But I think I'll close this issue because I mainly wanted the cool badge.
