### ISSUE TITLE
Blackbox functions return tainted value (false positives)

### ISSUE THREAD

**Issue by KevinHock** [python-security/pyt#45]
So, there are 2 commented out tests that I added during my interprocedural PR [here](https://github.com/python-security/pyt/blob/master/tests/vulnerabilities_across_files_test.py#L49) and [here](https://github.com/python-security/pyt/blob/master/tests/vulnerabilities_across_files_test.py#L67). 

I was going to fix these via doing something in an `else` of this if in [visit_call](https://github.com/python-security/pyt/blob/master/pyt/interprocedural_cfg.py#L365), marking `node.something` as blackbox but I'm wondering what the best place to check `something` at, maybe [in reaching_definitions_base](https://github.com/python-security/pyt/blob/master/pyt/reaching_definitions_base.py), or adding them to the sanitizers dictionary so they can be marked as sanitized [here](https://github.com/python-security/pyt/blob/master/pyt/vulnerabilities.py#L196).

Thoughts?

**Comment by Thalmann** [comment]
Hmm, i do not know if this even makes much sense.

The first example about absolute import will not even run(ImportError).
The second one will fail when we make the post.

So i do not think we need to support analysis of code the python interpreter does not even understand.

**Comment by stufkan** [comment]
In my opinion the best solution would be to mark it as a vulnerability and in some way indicate that it is due to the name not being imported. That way the developer is able to disregard the vulnerability if he knows that he uses some dynamic magic to set the name

**Comment by KevinHock** [comment]
I probably could have explained this better, say [this file](https://github.com/python-security/pyt/blob/master/example/vulnerable_code_across_files/absolute_from_file_does_not_exist.py) some_file could be any call from a library that we can't possibly know e.g. If all tainted args means a tainted return value. I'll change it to some library call that doesn't return a tainted value. 

So we shouldn't report it as a vulnerability with as much confidence as everything else. We can talk more about the UI part when I make the PR on Monday or Tuesday.

The way I did this was, to put the call in a set called blackbox_calls and then check in the assignment_with_call type function if the call is in blackbox calls. If it is, I add the assignment to blackbox assignments, this will get more complicated when I handle nested function calls but I'll write tests and incrementally handle things.

**Comment by KevinHock** [comment]
One day we'll do it like [this awesome paper](https://www.doc.ic.ac.uk/~livshits/papers/tr/jscap_tr.pdf) but, we're not there yet.

**Comment by KevinHock** [comment]
Maybe [this update](https://github.com/python-security/pyt/commit/fee8d51be9ed8ed3c996a39c6aae90a38ad34f5b#diff-b08eee8fd69af19a31e454f05fa2d4ff) to the example file is better, thoughts? (Why would you exec an scrypt hash is a valid question but I didn't feel like running pyt on stuff to find a better example.)
