### ISSUE TITLE
Delete repos after scanning

### ISSUE THREAD

**Issue by Thalmann** [python-security/pyt#5]
Check if clean up in repo runner works - it seems not.

**Comment by stufkan** [comment]
Note: It fills my harddrive!

**Comment by KevinHock** [comment]
Now that PyT is on PyPi, I think it would be best if I made a separate repo for the GitHub scanner code, for a clean separation between the two. Like [`detect-secrets`](https://github.com/Yelp/detect-secrets) and [`detect-secrets-server`](https://github.com/Yelp/detect-secrets-server). We can reference it from the README.
