### ISSUE TITLE
Write tests for __main__.py

### ISSUE THREAD

**Issue by KevinHock** [python-security/pyt#54]
As we can see on CodeClimate https://codeclimate.com/github/python-security/pyt/coverage/5935971dbf92ed000102998b there is pretty low test coverage of main, I understand why this is but adding some tests for it would increase our test coverage percentage and 75% isn't satisfying.

If you have any trouble with this I can help, I am going to label this issue as Easy so new comers see it.

**Comment by yongzx** [comment]
@KevinHock, can I contribute to solving this issue? (I am still a beginner in OS.)

**Comment by KevinHock** [comment]
Sure @yongzx, I can try to write the first test to give you a better idea of what I had in mind, I'll write it sometime today, push it to a branch, and let you know. Apologies for not doing this initially.

**Comment by yongzx** [comment]
Thanks! It's alright, I was just intending to ask you about the test you had in mind.

**Comment by KevinHock** [comment]
Hmm, so https://github.com/python-security/pyt/compare/54_tests_for_main is a test for what happens when we pass no args to the program. There is a problem though, if we look at __main__.py from https://codeclimate.com/github/python-security/pyt/coverage, the main() function is what we want more coverage on, so this is only a step closer to running main().

**Comment by KevinHock** [comment]
(Merged it so it's just easier than 2 people contributing to one branch.) I think the next step is to call main with random args (e.g. Print def use graph to a file) and make tests that verify it does what it currently does. Let me know if you'd like me to write the first of one of these.

**Comment by yongzx** [comment]
I will give it a try first. Thanks for the clarification.

**Comment by yongzx** [comment]
Just understood the codes in __main__.py and how the tests files go together. Will start writing a test for __main__.py.

**Comment by KevinHock** [comment]
Sounds good, thanks. Feel free to take your time, let me know if you need any help.

**Comment by KevinHock** [comment]
I did this in another branch already, gonna merge in a week or two, but I figured I would close this now.
