### ISSUE TITLE
No module named 'graphviz' error

### ISSUE THREAD

**Issue by soomonsoon** [python-security/pyt#60]
When attempting to run the intro example on XSS_reassign, I'm getting

ModuleNotFoundError: No module named 'graphviz'

Could someone help me out? I'm really excited to use pyt and ready to get started!

**Comment by KevinHock** [comment]
Hey @soomonsoon, sorry for the late reply, (I have recently been busy with interviews but I think I'm gonna sign an offer tomorrow), can you try out `pip3 install -r requirements.txt` and see if that works for you?

**Comment by KevinHock** [comment]
Gonna close this but reopen/Let me know if you still have any problems.
