### ISSUE TITLE
Has anyone found the possibility to recursively scan files ?

### ISSUE THREAD

**Issue by Storm75** [python-security/pyt#61]
How would you scan a whole django repository ?
I may be wrong but it seems that this product misses a very trivial feature...

**Comment by Pawamoy** [comment]
With other programs like `find` and `xargs`?

```
find . -iname "*.py" -exec pyt -f {} \;
find . -iname "*.py" | xargs -n1 pyt -f
```

It will scan each file one by one (not as a whole).

**Comment by KevinHock** [comment]
So we currently require that you point pyt at controller files yourself (see https://github.com/python-security/pyt/pull/52 for the relevant code) but after an issue I think is high-priority (https://github.com/python-security/pyt/issues/45) is solved maybe I'll work on framework entry-points or Python2 support or some other trivial feature...

**Comment by KevinHock** [comment]
So this was done for real with the `-r` flag.
