### ISSUE TITLE
Dynamic partitioning of date interval in github search

### ISSUE THREAD

**Issue by Thalmann** [python-security/pyt#7]

**Comment by Thalmann** [comment]
Wait for https://github.com/python-security/pyt/issues/8

**Comment by KevinHock** [comment]
Now that PyT is on PyPi, I think it would be best if I made a separate repo for the GitHub scanner code, for a clean separation between the two. Like [`detect-secrets`](https://github.com/Yelp/detect-secrets) and [`detect-secrets-server`](https://github.com/Yelp/detect-secrets-server). We can reference it from the README.
