### ISSUE TITLE
Add framework adaptor option for Django

### ISSUE THREAD

**Issue by KevinHock** [python-security/pyt#71]
A good heuristic for what a Django controller is is that it has request as the first argument. This is easy enough to implement in an hour by looking at https://github.com/python-security/pyt/pull/52/files though, if you're interested.

**Comment by davidoc** [comment]
I'm looking into this. It would be nice to also support [class-based views](https://docs.djangoproject.com/en/1.11/topics/class-based-views/).

**Comment by KevinHock** [comment]
Woohoo! Great working with you, you can close the PR and get the green square if you'd like :)
