### ISSUE TITLE
Virtual env setup guide

### ISSUE THREAD

**Issue by Thalmann** [python-security/pyt#9]

**Comment by KevinHock** [comment]
# Virtual env setup guide

`mkdir ~/pyt`
`cd ~/pyt`
`git clone https://github.com/python-security/pyt.git`
`python3 -m venv ~/pyt/`
`python --version`
`pip --version`
`cd pyt`
`pip install -r requirements.txt`
`pip list`

In the future, just type `source ~/pyt/bin/activate` to start developing.

**Comment by KevinHock** [comment]
Any edits I should make? Should I add it in a section in the README?

**Comment by KevinHock** [comment]
Added it to my latest PR https://github.com/python-security/pyt/pull/23

**Comment by Thalmann** [comment]
LGTM - thanks! :)
